### ISSUE TITLE
wheres da code

### ISSUE THREAD

**Issue by Minhe173** [Scripped/Roblox-Banned-User-Viewer#1]

**Comment by Scripped** [comment]
lol im not finished with it yet, it should be ready soon! 😊

**Comment by Scripped** [comment]
ive put up some pictures of what it looks like now on README.md if you wanna see how far ive gotten to finishing😁

**Comment by Scripped** [comment]
![3](https://user-images.githubusercontent.com/69485097/163667696-9a39a6b5-d800-40ad-8bdf-58c9873b46ee.JPG)
![2](https://user-images.githubusercontent.com/69485097/163667697-3d192f83-8d0a-43ee-bb93-61d41cf46525.JPG)
![1](https://user-images.githubusercontent.com/69485097/163667701-7a2b6450-2dfc-46e1-99c1-8bc86e9371f6.JPG)
![friends](https://user-images.githubusercontent.com/69485097/163667703-9084a9b4-e8f2-4c4f-9580-24a9f362ff4c.JPG)
